### ISSUE TITLE
Add systemd to make it work on Ubuntu 15 & Debian 8 and future versions

### ISSUE THREAD

**Issue by jordigg** [grundic/puppet-teamcity#5] opened 2016-01-08 14:44 UTC
Ubuntu 15 and Debian 8 started using systemd for managing services. A build-agent.service file is needed in /lib/systemd/system/ with the following content:
```
[Unit]
Description=TeamCity build agent

[Service]
User=teamcity #specify user running agent
ExecStart=/home/teamcity/BuildAgent/bin/agent.sh run #specify folder where teamcity is installed

[Install]
WantedBy=multi-user.target
```

**Comment by jordigg** [comment] 2016-01-08 18:38
Sent PR #6 with my fix. Tested and works just fine on Ubuntu 15.10, haven't tested on Debian 8 yet.

**Comment by grundic** [comment] 2016-01-08 21:12
Hi, @jordigg,
Thank you for your work! I'll check it soon.

**Comment by grundic** [comment] 2016-01-08 22:38
Well, it looks like it still uses init.d -- in config.pp now there are two independent file declarations for init.d and systemd. And because the service provider by default is init.d, Puppet executes it as before. 
To make it work we need add additional parameter, say `service_type` (although there is already similar `$service_run_type` so maybe they could be joined) and depending on it use appropriate configuration file and set service provider either `init` or `systemd`.

Still good job, but need some improvements.

**Comment by jordigg** [comment] 2016-01-08 23:48
I wanted to add that issue as comment but wasn't sure. Ubuntu 15.10 when init.d is called forwards the call to systemd but it may get deprecated on future versions.

I'll check if the system have systemd or not and then setup the correct method to start the system. If this is not possible then we'll need the parameter. Would that be OK o better to let the user choose?

I'm just learning by doing, I'm new to Puppet and scripting on Linux. I'm automating everything I can at work and that's why I'm trying to update your work.

Thanks for checking and thanks for the module @grundic.

**Comment by grundic** [comment] 2016-01-09 00:08
Even if calls to `service` are forwarded from init.d to systemd, I think it's not very good to keep to configuration files for different services.
I would recommend to take a look at this module: https://github.com/elastic/puppet-elasticsearch. It has support of both initialisation systems, so we can do something similar.
Here how it could look like:
**config.pp**
```
case $service_run_type {
      'init': {
        file { '/etc/init.d/build-agent':
          ensure  => 'present',
          owner   => 'root',
          group   => 'root',
          mode    => '0755',
          content => template("${module_name}/build-agent.erb"),
        }
      }
      'systemd': {
        file { '/lib/systemd/system/build-agent.service':
          ensure  => 'present',
          owner   => 'root',
          group   => 'root',
          mode    => '0755',
          content => template("${module_name}/build-agent-service.erb"),
        }
      }
    }
```
**service.pp**
```
service { 'build-agent':
      ensure     => $service_ensure,
      enable     => $service_enable,
      hasstatus  => true,
      hasrestart => true,
      provider   => $service_run_type,
      require    => $service_run_type ? {
        'init' => File['/etc/init.d/build-agent'],
        'systemd' => File['/lib/systemd/system/build-agent.service'],
      }
    }
```

I checked module with this settings on Vagrant machine, but for some reason systemd fails with timeout:
```
vagrant@vagrant-ubuntu-wily-64:~$ sudo service build-agent start
Job for build-agent.service failed because a timeout was exceeded. See "systemctl status build-agent.service" and "journalctl -xe" for details.
``` 
Have you run it successfully? 

I'm glad you are improving your knowledge and wish you all the best :) Keep going, and don't let small mistakes stop you!

**Comment by jordigg** [comment] 2016-01-09 14:31
Yes works fine for me. I'm on Ubuntu 15.10. Puppet Server is running on Debian 8.

Updated my fork with your suggestions and finished the rest. If you want to check it is over here: https://github.com/jordigg/puppet-teamcity/

What you get when checking the logs or  by doing a 'sudo service build-agent status'? Which OS are you using?

**Comment by grundic** [comment] 2016-01-10 13:16
I run puppet apply without puppet master on virtualbox via vagrant. Here my tc.pp file:
```puppet
class {'::teamcity::agent':
  agent_name            => 'sample-build-agent',
  download_url           => 'https://teamcity.jetbrains.com/update/buildAgent.zip',
  manage_user           => true,
  manage_group          => true,
  service_run_type      => 'systemd',
  custom_properties     => {
      'system.teamcity.idea.home' => '%system.agent.home.dir%/tools/idea'
  },
  launcher_wrapper_conf => {
    'wrapper.app.parameter.11' => '-Dfile.encoding=UTF-8'
  }
}
```

And here is output from `sudo puppet apply tc.pp`:
```
vagrant@vagrant-ubuntu-wily-64:~$ sudo puppet apply tc.pp
Warning: Config file /etc/puppet/hiera.yaml not found, using Hiera defaults
Notice: Compiled catalog for vagrant-ubuntu-wily-64 in environment production in 1.15 seconds
Notice: /Stage[main]/Teamcity::Agent::Install/Wget::Fetch[teamcity-buildagent]/Exec[wget-teamcity-buildagent]/returns: executed successfully
Notice: /Stage[main]/Teamcity::Agent::Install/Exec[extract-agent-archive]/returns: executed successfully
Notice: /Stage[main]/Teamcity::Agent::Install/File[/opt/build-agent/bin/agent.sh]/mode: mode changed '0644' to '0755'
Notice: /Stage[main]/Teamcity::Agent::Install/File[agent-config]/ensure: defined content as '{md5}b7b353774bd93642e668e5d75f32b911'
Notice: /Stage[main]/Teamcity::Agent::Install/Exec[chown-agent-dir]: Triggered 'refresh' from 1 events
Notice: /Stage[main]/Teamcity::Agent::Config/File[/lib/systemd/system/build-agent.service]/ensure: created
Notice: /Stage[main]/Teamcity::Agent::Config/Ini_setting[[] wrapper.app.parameter.11]/ensure: created
Notice: /Stage[main]/Teamcity::Agent::Config/Ini_setting[[] system.teamcity.idea.home]/ensure: created
' to 'http://builder'Teamcity::Agent::Config/Ini_setting[[] serverUrl]/value: value changed 'http://localhost:8111/
' to 'sample-build-agent'city::Agent::Config/Ini_setting[[] name]/value: value changed '
Error: Could not start Service[build-agent]: Execution of '/bin/systemctl start build-agent' returned 1: Warning: build-agent.service changed on disk. Run 'systemctl daemon-reload' to reload units.
Job for build-agent.service failed because a timeout was exceeded. See "systemctl status build-agent.service" and "journalctl -xe" for details.
Wrapped exception:
Execution of '/bin/systemctl start build-agent' returned 1: Warning: build-agent.service changed on disk. Run 'systemctl daemon-reload' to reload units.
Job for build-agent.service failed because a timeout was exceeded. See "systemctl status build-agent.service" and "journalctl -xe" for details.
Error: /Stage[main]/Teamcity::Agent::Service/Service[build-agent]/ensure: change from stopped to running failed: Could not start Service[build-agent]: Execution of '/bin/systemctl start build-agent' returned 1: Warning: build-agent.service changed on disk. Run 'systemctl daemon-reload' to reload units.
Job for build-agent.service failed because a timeout was exceeded. See "systemctl status build-agent.service" and "journalctl -xe" for details.
Notice: /Stage[main]/Teamcity::Agent::Service/Service[build-agent]: Triggered 'refresh' from 1 events
Notice: Finished catalog run in 104.45 seconds
```

Also I think we need to add special Exec for executing systemd reload, like [here](https://github.com/elastic/puppet-elasticsearch/blob/master/manifests/service/systemd.pp#L195), but still, running this command manually `sudo systemctl daemon-reload` and then `sudo systemctl start build-agent.service` also gives me timeout error.

You can install the box to vagrant like this:
```vagrant box add ubuntu/wily64 ```
And try to run my example, maybe you have some local modifications in place. Otherwise, you should receive same result as me.

**Comment by jordigg** [comment] 2016-01-11 08:31
I'll give it a try today. Just got to the office and we don't have any power :electric_plug: 

I'll check about the systemd reload and maybe add some more things following the example of elasticsearch. Just to make sure we clean the service file in case the user moves from systemd to init.

**Comment by jordigg** [comment] 2016-01-12 18:37
I just tested with the Ubuntu/Wily64 box and saw the timeout. Changed the `ExecStart` parameter on the .service file from `run` to `start`. I think by using `run` (the script runs on the same console so systemd thinks is always "starting" and timesout. With `start` the process goes on the background and works. the first run may take longer because the agent sometimes updates itself.

I'll add now the `systemctl daemon-reload` required every time the service file changes just to make sure we don't have problems here with future updates.

Another bug is that on unix `manage_agent_user_home` doesn't work. Just on windows it creates the home folder so it makes the install process fail because can't extract the files on a non-existent folder. I'll add that fix as well.

Then I had puppet errors trying when unziping the downloaded file. The code is this:
```
exec { 'extract-agent-archive':
      command   => "unzip /tmp/${archive_name} -d ${agent_dir}",
      creates   => "${agent_dir}/conf",
      logoutput => 'on_failure',
      require   => Wget::Fetch['teamcity-buildagent']
    }
```

Changing `command   => "unzip /tmp/${archive_name} -d ${agent_dir}",` for `command   => "unzip /tmp/${archive_name} -d ${agent_dir}",` did the trick. Maybe `/tmp/` isn't always the temp path? I'll update that as well.

I think with these changes we should be good to go for now. With more time I'll try to make it more similar to the elasticsearch example.

**Comment by grundic** [comment] 2016-01-13 10:07
Hi, @jordigg!
Excellent news, I'm glad you could reproduce the issue and find out the cause of it.
What about the `unzip` command -- good catch and actually this module already has custom fact `temp_dir `, which is used in `agent/install.pp` for Windows installation. I think it's a good idea for robustness and consistency to use it for Linux as well.
Thank you very much for you contribution!

**Comment by jordigg** [comment] 2016-01-13 11:04
Yes, that's the change. Forgot to add the correct line on my last comment. Now linux installation are using the "${::temp_dir}" fact to know where to get the job done.

Seems I'm having some other problems and it's that by running the service using the `teamcity` user and `teamcity` group or any other non-admin account makes the update enter an infinite loop because don't have enough permissions to perform it.
The update requires downloading, extracting plugins and a new `BuildAgent.zip` file and running it later. A non admin account can't stop/start services itself so I think that's the problem here.
We may require that linux accounts are set to be sudo. I'm checking now how to fix it. When I run the `agent.sh start` manually works fine so that's why I'm guessing it may be related to permissions.

**Comment by jordigg** [comment] 2016-01-13 11:54
OK, final version...
Had to fix again the .service file. Seems that running "/bin/agent.sh run" but without Forking mode fixed the permissions issue and allows the correct update of the agent.

I think I don't have more to add now. What you think? Is it good to be merged?

**Comment by grundic** [comment] 2016-01-14 09:42
Hi, @jordigg,
So, there still some issues:
```
Error: unzip /tmpbuildAgent.zip -d /opt/build-agent returned 9 instead of one of [0]
```

You forget to put slash between `temp_dir` and `archive_name`, changing it to 
```"unzip ${::temp_dir}/${archive_name} -d ${agent_dir}"```
fixed the problem.
Actually, when you want to check fresh installation you can just remove all related stuff with this command:
```
sudo rm -rf /etc/init.d/build-agent /lib/systemd/system/build-agent.service /opt/build-agent/
```

There is another issue, but I think it's not related to your changes: first time puppet applies manifest the server is not started, but it only executed on second run. I think it should be fixed, I'll try to figure it out maybe a little bit later.
Also `puppet-lint` gives some new warnings, if you like, you can check them, but again, I can take care about it myself.
Porting module to MacOS sounds great :) Thank you again for your contributions!

**Comment by grundic** [comment] 2016-01-14 09:45
Ooups, it still doesn't starts the service:
```bash
vagrant@vagrant-ubuntu-wily-64:~$ sudo puppet apply tc.pp
Warning: Config file /etc/puppet/hiera.yaml not found, using Hiera defaults
Notice: Compiled catalog for vagrant-ubuntu-wily-64.ad.here.com in environment production in 0.94 seconds
Notice: /Stage[main]/Teamcity::Agent::Service/Service[build-agent]/ensure: ensure changed 'stopped' to 'running'
Notice: Finished catalog run in 0.18 seconds
vagrant@vagrant-ubuntu-wily-64:~$
vagrant@vagrant-ubuntu-wily-64:~$ ps aux | grep java
vagrant   2112  0.0  0.1   8188  1828 pts/0    S+   09:43   0:00 grep --color=auto java
```

**Comment by jordigg** [comment] 2016-01-14 11:15
"/" fixed. That what happen when I do the edits directly on Github website...
I'll check that too. I have always to run my puppet twice because my Java fails to install the first time. I'm using https://forge.puppetlabs.com/spantree/java8 because it works on latests Ubuntu and Debian versions.
Will try another Java module and have a successful run on the first try.

**Comment by jordigg** [comment] 2016-01-14 11:21
@grundic how do you get your Java installed on Ubuntu Wily? tried with the official Puppet module for it but doesn't seem to be compatible yet.

**Comment by grundic** [comment] 2016-01-14 11:31
@jordigg, usually I use Java from *webupd8team* ppa manually, using this instruction: https://www.digitalocean.com/community/tutorials/how-to-install-java-on-ubuntu-with-apt-get. It's most quick and easy way, because Puppet modules are not updated regularly, so it's easier to install it this way.

**Comment by jordigg** [comment] 2016-01-14 12:35
Tried again and works just fine. I made a checkpoint on the vagrant box just after setting up the agent with the master, I restore to that point before every try.
Here is my manifest if can help.

```
class base::basics {
	$packages = ['unzip', 'python-software-properties']

	exec { "update":
    	command => "/usr/bin/apt-get update",
    }

    package { $packages:
            ensure => installed,
            require => Exec["update"],
    }
}

class base::java8 {
	exec { "add-repo-java":
            command => "/usr/bin/add-apt-repository -y \"ppa:webupd8team/java\" && /usr/bin/apt-get update"
    }

    exec { "set-accept":
            command => "/bin/echo /usr/bin/debconf shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections && /bin/echo /usr/bin/debconf shared/accepted-oracle-license-v1-1 seen true | sudo /usr/bin/debconf-set-selections",
            require => Exec['add-repo-java'],
    }

    exec { "install":
            command => "/usr/bin/apt-get install -y oracle-java8-installer",
            require => Exec['set-accept'],
    }

    exec { "setup_home":
            command => "/bin/echo \"export JDK18_HOME=/usr/lib/jvm/java-8-oracle/\" >> /etc/environment",
            require => Exec['install'],
    }
}

class agent::linux {

	class {'::teamcity::agent':
		agent_name				=> 'ubuntu-wily',
		agent_user				=> 'teamcity',
		agent_user_home			=> '/home/teamcity/',
		manage_agent_user_home 	=> true,
		agent_group				=> 'teamcity',
		manage_user				=> true,
		manage_group			=> true,
		server_url				=> 'http://black-teamcity.resources.local',
		archive_name			=> 'buildAgent.zip',
		download_url			=> 'http://black-teamcity.resources.local/update/buildAgent.zip',
		agent_dir				=> '/home/teamcity/BuildAgent',
		service_ensure			=> running,
		service_enable			=> true,
		service_run_type		=> 'systemd',
	}

	#python + pip
	class { 'python' :
		version    => 'system',
		pip        => 'present',
		dev        => 'absent',
		virtualenv => 'absent',
		gunicorn   => 'absent',
	}

	#semantic_version
	python::pip { 'semantic_version' :
	    pkgname       => 'semantic_version',
	    ensure        => 'present'
	}

	#sphinx
	python::pip { 'sphinx' :
		pkgname	=> 'sphinx',
		ensure 	=> 'present'
	}

	#Required packages specific for builds
	package { 'cmake':
		ensure  => 'present'
	}
}

node 'vagrant-ubuntu-wily-64.local' {

	include base::basics
	include base::java8
	include agent::linux

}
```

**Comment by grundic** [comment] 2016-01-14 13:50
Okay, I'll check it.

**Comment by jordigg** [comment] 2016-01-14 18:09
Updated my manifest now is a bit cleaner when installing java. I just tried and I could install Java 1.8.0_66 using this package `openjdk-8-jre-headless`. Teamcity agent runs fine on it.

**Comment by grundic** [comment] 2016-01-15 17:25
So, I tried it again without no luck.
Investigating the problem I found that we have to use `Type=forking`, because agent.sh file is not the process that is executed, but it triggers Java inside of it.
Actually, checking the histroy I found that [this one ](https://github.com/jordigg/puppet-teamcity/commit/7789128278ef24ca2c41a0324fcfdce21b97794e) looks very good and maybe you could apply it to your pull request?

**Comment by jordigg** [comment] 2016-01-15 18:09
I'll update it now. Last time I tried with it it triggered an infinite loop updating the agent on the first run. Now seems to work just fine.
Do you have logs from `systemctl` and `/home/teamcity/BuildAgent/logs/teamcity-agent.log`?
Firs time I tried you module with the default parameters on the manifest it fail to install what I needed. Then I tried to set all parameters on the manifest and worked fine. Now I'm always testing defining all parameters on the manifest, I'll have to try just defining those that are different from default to see if it's a bug.

**Comment by jordigg** [comment] 2016-01-20 09:29
Yesterday I got this error:
```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: No matching entry for selector parameter with value 'service_run_type' at /etc/puppetlabs/code/environments/production/modules/teamcity/manifests/agent/service.pp:56:21
```
I have checked the files and I have a default param set in 'params.pp'. Do you know why I get this errors? This time I'm trying to use Hiera, I don't know if it can be related.

**Comment by grundic** [comment] 2016-01-20 12:45
I think it happened either because version 4 of Puppet or because of enabled future parser.
In any case, looks like puppet lint doesn't like declaring selector inside resource block:
```
vagrant@vagrant-ubuntu-wily-64:~$ puppet lint /etc/puppet/modules/teamcity/manifests/agent/service.pp
WARNING: selector inside resource block on line 56
```

Maybe taking selector outside could solve your issue.

**Comment by jordigg** [comment] 2016-01-20 13:30
Ok, fixed!
Now I'm back at the bug that default values aren't overwritten if I don't specify all the variables by hand but isn't related to my PR, I'll take a look now. Have you got luck running it yet?

**Comment by jordigg** [comment] 2016-01-20 14:34
Fixed the bug with the params. Some of them were missing on the `params.pp` file so they were never picking the values set on Hiera. I think everything works now. Do you want to check and update the module on Forge?

**Comment by grundic** [comment] 2016-01-20 14:51
Yep, I will check it today and try to release. Thank you for contribution!

**Comment by grundic** [comment] 2016-01-20 23:15
Version 1.1.0 released Jan 21st 2016.
Again, thank you for your work.

**Closed by grundic** 2016-01-20 23:15 UTC
